export const HOTEL_LIST_REQUEST = 'HOTEL_LIST_REQUEST';
export const HOTEL_LIST_SUCCESS = 'HOTEL_LIST_SUCCESS';
export const HOTEL_LIST_FAIL = 'HOTEL_LIST_FAIL';

export const HOTEL_DETAILS_REQUEST = 'HOTEL_DETAILS_REQUEST';
export const HOTEL_DETAILS_SUCCESS = 'HOTEL_DETAILS_SUCCESS';
export const HOTEL_DETAILS_FAIL = 'HOTEL_DETAILS_FAIL';

export const HOTEL_DELETE_REQUEST = 'HOTEL_DELETE_REQUEST';
export const HOTEL_DELETE_SUCCESS = 'HOTEL_DELETE_SUCCESS';
export const HOTEL_DELETE_FAIL = 'HOTEL_DELETE_FAIL';

export const HOTEL_UPDATE_REQUEST = 'HOTEL_UPDATE_REQUEST';
export const HOTEL_UPDATE_SUCCESS = 'HOTEL_UPDATE_SUCCESS';
export const HOTEL_UPDATE_FAIL = 'HOTEL_UPDATE_FAIL';
export const HOTEL_UPDATE_RESET = 'HOTEL_UPDATE_RESET';