export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_VALIDATE_REQUEST = 'ORDER_VALIDATE_REQUEST';
export const ORDER_VALIDATE_SUCCESS = 'ORDER_VALIDATE_SUCCESS';
export const ORDER_VALIDATE_FAIL = 'ORDER_VALIDATE_FAIL';
export const ORDER_VALIDATE_RESET = 'ORDER_VALIDATE_RESET';